Fix `ResolveParameterWithBase` bug (which is broken now)
go-openapi/spec pull request #128
Opened 2020-11-24 14:41 UTC by magodo

When the `opts` is set with `RelativeBase` set, current `ResolveParameterWithBase` will just fail. Referring to the implementation of `ResolveWithBase`, adding the missing part to make it work.

2020-11-24 16:01 UTC, fredbi requested changes
@magodo

Could you please give an example of the broken feature and add it to the unit tests to assert that your fix works fine?

2020-11-24 16:06 UTC, fredbi commented
also if `ResolveParameterWithBase` is broken, so is probably `ResolveResponseWithBase`, which follows the same logic. But you didn't address that part.

2020-11-27 12:22 UTC, magodo commented
@fredbi Thank you for the feedbacks! I have done the same change onto `ResolveResponseWithBase`, and added UT(s) for both.
Please take another look!

2020-11-27 13:20 UTC, fredbi commented
@magodo  your PR looks good to me

Could you please rebase and PGP-sign your commit. Then I'll merge straight away.

Thank you for contributing!

2020-11-28 03:30 UTC, magodo commented
@fredbi I have squashed and rebased the commit and signed off it. Thank your for reviewing :)

2020-11-28 04:46 UTC, fredbi commented
@magodo we are almost good...
I've reactived the linter in CI... (was disabled for sometime, as golangci ceased to operate).

Just need to address this:
```
expander_test.go:308:10: string `fixtures/expansion/crossFileRef.json` has 2 occurrences, make it a constant (goconst)

	path := "fixtures/expansion/crossFileRef.json"
```

2020-11-28 04:54 UTC, fredbi commented
I've added #130 that should merge your PR automatically when applied

2020-11-28 05:10 UTC, fredbi commented
@magodo I've merged your commit (with #130), with the linter issue fixed. Thank you so much for picking this one.

2020-11-28 05:10 UTC, closed without merging